language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - bin/list-all
  - asdf plugin-add heptio-authenticator-aws ./
  - asdf list-all heptio-authenticator-aws
  - asdf plugin-test heptio-authenticator-aws ./ 'heptio-authenticator-aws'

os:
  - linux
  - osx
